'use client';

import { ArrowLeft, Download, CheckCircle2, AlertCircle } from 'lucide-react';
import { useRouter, useParams } from 'next/navigation';
import { useRef } from 'react';

export default function CRMReportPage() {
  const router = useRouter();
  const params = useParams();
  const reportRef = useRef(null);

  const reportData = {
    title: 'CRM Report — Loan Application Summary',
    reportDate: '04 November 2025',
    generatedBy: 'John Doe / 03:45 CRM',
    department: 'Loan Management',
    clientInfo: {
      name: 'Niharika Rastogi',
      age: '26',
      contact: '9876543210',
      email: 'niharika@gmail.com',
      location: 'Noida'
    },
    loanDetails: {
      type: 'Business',
      status: 'Initiated',
      amountRequested: '5 Lakhs',
      proposedInterest: '9.5%',
      repaymentTerm: 'Medium-term',
      creditScore: '725'
    },
    leadSource: {
      source: 'Online Inquiry',
      leadDate: '01 November 2025',
      followUpDate: '03 November 2025',
      response: 'Responsive with CRM'
    },
    communicationLog: [
      {
        date: '1 Nov 2025',
        type: 'Email',
        status: 'Informative email sent to the client'
      },
      {
        date: '2 Nov 2025',
        type: 'Call',
        status: 'Not responsive',
        notes: 'Client mentioned that business plans are being finalised and will revert with paperwork'
      }
    ],
    verificationStatus: [
      {
        item: 'Verification of KYC documents',
        status: 'completed',
        notes: 'Adhaar and PAN card verified'
      },
      {
        item: 'Business Registration',
        status: 'pending',
        notes: 'To be approved within three days'
      }
    ],
    feedback: {
      text: 'Client was well-informed about Lead Application and expressed satisfaction with the follow-up process',
      needs: [
        'Requires a quick approval process',
        'Prefers e-auction faster start-up call',
        'Needs simplified documentation',
        'Unclear about the email once the file is approved',
        'Update client on email once the file is approved'
      ]
    }
  };

  const handleDownloadPDF = async () => {
    // Using browser's print functionality to generate PDF
    // For production, use libraries like jsPDF or react-pdf
    window.print();
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header - No print */}
      <div className="sticky top-0 z-40 g-gradient-to-r from-purple-900 to-indigo-900 p-4 flex items-center justify-between shadow-lg print:hidden">
        <div className="flex items-center gap-4">
          <button 
            onClick={() => router.back()}
            className="text-white hover:bg-white/10 p-2 rounded-lg transition"
          >
            <ArrowLeft size={24} />
          </button>
          <h1 className="text-white text-xl font-bold">Report</h1>
        </div>
        <button
          onClick={handleDownloadPDF}
          className="flex items-center gap-2 bg-white text-purple-900 px-4 py-2 rounded-lg font-semibold hover:bg-gray-100 transition"
        >
          <Download size={18} />
          <span className="hidden sm:inline">Download PDF</span>
        </button>
      </div>

      {/* Report Content */}
      <div className="max-w-4xl mx-auto p-4 sm:p-6 lg:p-8" ref={reportRef}>
        <div className="bg-white rounded-2xl shadow-lg print:shadow-none print:rounded-none">
          {/* Report Header */}
          <div className="g-gradient-to-r from-purple-900 to-indigo-900 p-6 sm:p-8 rounded-t-2xl print:rounded-none text-white">
            <h1 className="text-2xl sm:text-3xl font-bold mb-4">{reportData.title}</h1>
            <div className="space-y-2 text-sm sm:text-base">
              <p><span className="font-semibold">Report Date:</span> {reportData.reportDate}</p>
              <p><span className="font-semibold">Generated by:</span> {reportData.generatedBy}</p>
              <p><span className="font-semibold">Department:</span> {reportData.department}</p>
            </div>
          </div>

          {/* Report Body */}
          <div className="p-6 sm:p-8 space-y-8">
            {/* Client Information */}
            <section>
              <h2 className="text-xl font-bold text-gray-800 mb-4 border-b-2 border-purple-600 pb-2">
                Client Information
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-3">
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Name:</span>
                    <span className="text-gray-800 font-semibold">{reportData.clientInfo.name}</span>
                  </div>
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Age:</span>
                    <span className="text-gray-800">{reportData.clientInfo.age}</span>
                  </div>
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Contact:</span>
                    <span className="text-gray-800">{reportData.clientInfo.contact}</span>
                  </div>
                </div>
                <div className="space-y-3">
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Email:</span>
                    <span className="text-gray-800 text-sm break-all">{reportData.clientInfo.email}</span>
                  </div>
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Location:</span>
                    <span className="text-gray-800">{reportData.clientInfo.location}</span>
                  </div>
                </div>
              </div>
            </section>

            {/* Loan Details */}
            <section>
              <h2 className="text-xl font-bold text-gray-800 mb-4 border-b-2 border-purple-600 pb-2">
                Loan Details
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-3">
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Loan Type:</span>
                    <span className="text-gray-800 font-semibold">{reportData.loanDetails.type}</span>
                  </div>
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Status:</span>
                    <span className="text-gray-800">{reportData.loanDetails.status}</span>
                  </div>
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Amount Requested:</span>
                    <span className="text-gray-800">{reportData.loanDetails.amountRequested}</span>
                  </div>
                </div>
                <div className="space-y-3">
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Proposed Interest:</span>
                    <span className="text-gray-800">{reportData.loanDetails.proposedInterest}</span>
                  </div>
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Repayment Term:</span>
                    <span className="text-gray-800">{reportData.loanDetails.repaymentTerm}</span>
                  </div>
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Credit Score:</span>
                    <span className="text-gray-800 font-semibold">{reportData.loanDetails.creditScore}</span>
                  </div>
                </div>
              </div>
            </section>

            {/* Lead Source & Assignment */}
            <section>
              <h2 className="text-xl font-bold text-gray-800 mb-4 border-b-2 border-purple-600 pb-2">
                Lead Source & Assignment
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-3">
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Source:</span>
                    <span className="text-gray-800">{reportData.leadSource.source}</span>
                  </div>
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Lead Date:</span>
                    <span className="text-gray-800">{reportData.leadSource.leadDate}</span>
                  </div>
                </div>
                <div className="space-y-3">
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Follow-up Date:</span>
                    <span className="text-gray-800">{reportData.leadSource.followUpDate}</span>
                  </div>
                  <div className="flex justify-between py-2 border-b border-gray-200">
                    <span className="text-gray-600 font-medium">Response:</span>
                    <span className="text-gray-800">{reportData.leadSource.response}</span>
                  </div>
                </div>
              </div>
            </section>

            {/* Communication Log */}
            <section>
              <h2 className="text-xl font-bold text-gray-800 mb-4 border-b-2 border-purple-600 pb-2">
                Communication Log
              </h2>
              <div className="space-y-4">
                {reportData.communicationLog.map((log, index) => (
                  <div key={index} className="bg-gray-50 p-4 rounded-lg border border-gray-200">
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-2">
                      <div>
                        <span className="text-gray-600 text-sm font-medium">Date:</span>
                        <p className="text-gray-800 font-semibold">{log.date}</p>
                      </div>
                      <div>
                        <span className="text-gray-600 text-sm font-medium">Type:</span>
                        <p className="text-gray-800 font-semibold">{log.type}</p>
                      </div>
                      <div>
                        <span className="text-gray-600 text-sm font-medium">Status:</span>
                        <p className="text-gray-800">{log.status}</p>
                      </div>
                    </div>
                    {log.notes && (
                      <div className="mt-2 pt-2 border-t border-gray-300">
                        <span className="text-gray-600 text-sm font-medium">Notes:</span>
                        <p className="text-gray-700 text-sm mt-1">{log.notes}</p>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </section>

            {/* Verification Status */}
            <section>
              <h2 className="text-xl font-bold text-gray-800 mb-4 border-b-2 border-purple-600 pb-2">
                Verification Status
              </h2>
              <div className="space-y-4">
                {reportData.verificationStatus.map((item, index) => (
                  <div key={index} className="bg-gray-50 p-4 rounded-lg border border-gray-200">
                    <div className="flex items-start gap-3">
                      {item.status === 'completed' ? (
                        <CheckCircle2 className="text-green-500 shrink-0 mt-1" size={20} />
                      ) : (
                        <AlertCircle className="text-orange-500 shrink-0 mt-1" size={20} />
                      )}
                      <div className="flex-1">
                        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-2 mb-2">
                          <span className="text-gray-800 font-semibold">{item.item}</span>
                          <span className={`text-sm font-semibold px-3 py-1 rounded-full ${
                            item.status === 'completed' 
                              ? 'bg-green-100 text-green-700' 
                              : 'bg-orange-100 text-orange-700'
                          }`}>
                            {item.status === 'completed' ? 'Completed' : 'Pending'}
                          </span>
                        </div>
                        <p className="text-gray-600 text-sm">{item.notes}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </section>

            {/* Feedback and Notes */}
            <section>
              <h2 className="text-xl font-bold text-gray-800 mb-4 border-b-2 border-purple-600 pb-2">
                Feedback and Notes
              </h2>
              <div className="bg-purple-50 p-4 sm:p-6 rounded-lg border border-purple-200">
                <p className="text-gray-700 mb-4 leading-relaxed">{reportData.feedback.text}</p>
                <div className="space-y-2">
                  {reportData.feedback.needs.map((need, index) => (
                    <div key={index} className="flex items-start gap-2">
                      <span className="text-purple-600 mt-1">•</span>
                      <span className="text-gray-700">{need}</span>
                    </div>
                  ))}
                </div>
              </div>
            </section>
          </div>

          {/* Download Button - Only visible on screen, not in print */}
          <div className="p-6 sm:p-8 print:hidden">
            <button
              onClick={handleDownloadPDF}
              className="w-full g-gradient-to-r from-purple-900 to-indigo-900 text-white py-4 rounded-xl font-bold text-lg hover:opacity-90 transition shadow-lg flex items-center justify-center gap-2"
            >
              <Download size={20} />
              Download PDF
            </button>
          </div>
        </div>
      </div>

      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          body {
            print-color-adjust: exact;
            -webkit-print-color-adjust: exact;
          }
          
          .print\\:hidden {
            display: none !important;
          }
          
          .print\\:shadow-none {
            box-shadow: none !important;
          }
          
          .print\\:rounded-none {
            border-radius: 0 !important;
          }
          
          @page {
            margin: 1cm;
            size: A4;
          }
          
          * {
            break-inside: avoid;
          }
          
          section {
            page-break-inside: avoid;
          }
        }
      `}</style>
    </div>
  );
}